### ISSUE TITLE
AT SOFT LAUNCH manually reset working primer plate dates

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#373] opened 2018-10-09 19:00 UTC
Once labman goes into use, working primer plate records can be created in labman at the time they are actually made.  However, for working primer plates that already exist at the time labman use begins, I think we will need to create those plates through the interface and then afterwards run a sql statement directly on the db to set the creation date to the correct one (in the past), rather than the date the records were created.  This should happen during the initial steps of soft launch (when the wet lab sets up their working primer plates and equipment) but will have to be performed by a technical person with direct database access.

**Comment by AmandaBirmingham** [comment] 2018-11-07 00:45
NB: this one cannot be done until soft launch happens--it is not something that is standing in the way of soft launch

**Comment by charles-cowart** [comment] 2019-04-01 19:24
Shotgun primer plates 'iTru 5 primer 2019-03-21' and 'iTru 7 primer 2019-03-21' have been added.

Confirmed that users creating primer working plates are able to change the date through the calendar widget, or directly. Hence, it is not necessary for a db admin to manually change the database entry to appear correctly. (It may still be beneficial to change the name of the Process tied to a primer plate's creation, as this may still reflect the day it was entered.)

- 

- [ ] Determine if there are any other working primer plates that are required for launch and add them.
- [ ] Remove 'iTru X primer 2019-03-27' working primer plates from labcontrol.ucsd.edu (test plates).
- [ ] Confirm dates do not need to be changed in Process list, else change them

**Comment by charles-cowart** [comment] 2019-04-04 19:07
Mostly sure run_dates do not need to be modified in Process table. The run_date is available to the Process() object as a property (date), however it's use appears limited to discussing Processes. It's not being used as the date for the iTru5 and iTru7 primers themselves.

**Comment by charles-cowart** [comment] 2019-04-04 19:23
I set the discarded flag on 'iTru 5 primer 2019-03-27' and 'iTru 7 primer 2019-03-27' entries in labman.plate to true. This has the intended effect of removing them from the Shotgun Library Prep page's 'Select i5/i7 primer plate' pull-downs. There are 384 wells associated with each (plate id 78, 79) in labman.well, however I don't think this is an issue.

**Comment by charles-cowart** [comment] 2019-04-04 20:58
I'm going to tentatively close this issue, as it doesn't seem reasonable to ask the Wet-lab to produce a canonical list of all working primer plates. Since we do appear to have working plates for both Shotgun and 16S, and we are able to create new plates through the UI with the correct date, we can add new ones on demand.

**Closed by charles-cowart** 2019-04-04 20:58 UTC
Labels: kludge, priority:high, scope:small
