### ISSUE TITLE
sample sheet can not contain duplicate blank values

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#205] opened 2018-02-20 21:05 UTC
trying to convert a current run, blank naming duplicates are not allowed when we utilize project naming and folders.  

example error:
Only 1 project is allowed for a given sampleId. SampleId: 'BLANK1_1A'.

**Comment by tanaes** [comment] 2018-02-20 22:40
in principle, this should not be a problem with the current db structure, right? B/c blanks are named uniquely per study and sample names have the study number prepended? 

Am I correct in that intuition, @josenavas ?

**Comment by AmandaBirmingham** [comment] 2019-04-19 18:28
@jdereus I'm trying to figure out how to address this issue in LabControl and I think I first need help from you to understand it better!  Could we possibly meet in person for 10-15 minutes sometime soon?

**Comment by jdereus** [comment] 2019-04-23 18:46
from what i can tell, this is just the fact that blanks also must be uniquely named.  not just samples.

if we need to get together to discuss, that's fine.

**Comment by AmandaBirmingham** [comment] 2019-04-25 20:02
Ah, but WHERE (in the LabControl output files) do the blank names that this issue is concerned with come from?  I'm going to guess from the sample sheet (obviously, correct me if I'm wrong!).  Below is a snippet from a current example of a sample sheet LabControl creates for a shotgun run (this issue is only relevant to shotgun, right?  Again, correct me if I'm wrong!) 


[Data] |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Lane | Sample_ID | Sample_Name | Sample_Plate | Sample_Well | I7_Index_ID | index | I5_Index_ID | index2 | Sample_Project | Well_Description
1 | 1_SKM6_640187_Test_plate_4_F12 | 1_SKM6_640187_Test_plate_4_F12 | Test_plate_4 | L24 | iTru7_115_07 | CACTAGCT | iTru5_119_H | GCGTTCTA | LabDude_PIDude_1 | 1.SKM6.640187.Test.plate.4.F12
1 | blank_Test_plate_1_H1 | blank_Test_plate_1_H1 | Test_plate_1 | O1 | iTru7_101_08 | CCTATGGT | iTru5_08_A | AGCAGATG | Controls | blank.Test.plate.1.H1
1 | blank_Test_plate_1_H10 | blank_Test_plate_1_H10 | Test_plate_1 | O19 | iTru7_107_08 | AGCTAACC | iTru5_08_G | ACGATGAC | Controls | blank.Test.plate.1.H10
1 | vibrio_positive_control_Test_plate_1_G1 | vibrio_positive_control_Test_plate_1_G1 | Test_plate_1 | M1 | iTru7_101_07 | ACTCGTTG | iTru5_07_A | GGTGTCTT | Controls | vibrio.positive.control.Test.plate.1.G1
1 | vibrio_positive_control_Test_plate_1_G10 | vibrio_positive_control_Test_plate_1_G10 | Test_plate_1 | M19 | iTru7_107_07 | CCGACTAT | iTru5_07_G | CGCTTAAC | Controls | vibrio.positive.control.Test.plate.1.G10
1 | vibrio_positive_control_Test_plate_1_G11 | vibrio_positive_control_Test_plate_1_G11 | Test_plate_1 | M21 | iTru7_108_03 | GAAGGTTC | iTru5_03_H | AAGCACTG | Controls | vibrio.positive.control.Test.plate.1.G11

It is currently the case (although may not have been when this issue was logged?) that `Sample_ID`
for blanks is the word `blank` followed by the name of the sample plate the blank came from (which must be universally unique within LabControl) followed by the well on that plate in which the blank was plated--e.g., `blank_Test_plate_1_H10`.  

@jdereus Do you believe this will be adequate for your downstream requirements?  Is it necessary to run a current sample sheet through your process in order to determine if this issue still exists?

**Comment by jdereus** [comment] 2019-04-25 20:10
That sounds like it would satisfy uniqueness requirements.

I do not know definitively if this is only for shotgun.  It _might_ crop up again as we are sometimes doing deeper sequencing on the MiSeq machine.  But that would be a question for wetlab people.  From a processing perspective, we just need uniqueness in all sample names.

**Comment by AmandaBirmingham** [comment] 2019-04-25 20:45
Hi, @jdereus can you confirm that the file whose contents we are discussing is the "sample sheet"? (I've attached a zipped example  since I know our terminology isn't entirely consistent :) 

[2019-04-25_samplesheet_test_shotgun_blank_test.csv.zip](https://github.com/jdereus/labman/files/3118806/2019-04-25_samplesheet_test_shotgun_blank_test.csv.zip)


*If so*, then I can confirm that this issue won't affect amplicon sequencing because the sample sheet format for amplicon sequencing does not include individual rows for blanks--instead, it has one row for each *pool* in the sequencing run, a la the example below: 


[Data] |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Lane | Sample_ID | Sample_Name | Sample_Plate | Sample_Well | I7_Index_ID | index | I5_Index_ID | index2 | Sample_Project | Well_Description
1 | plate 1 pool |   |   |   |   | NNNNNNNNNNNN |   |   | 5472

**Comment by jdereus** [comment] 2019-04-25 21:21
That file looks like it would process properly as what I consider to be a sample sheet.

Yes on amplicon sample sheet format.  With the requirement for the N’s or it will not process in MiSeq.  They are removed from the sample sheet when I go to complete the bcl conversion.

**Comment by AmandaBirmingham** [comment] 2019-04-25 22:31
Based on the discussion here, I conclude that this was a real issue when created, but that it was addressed along the way by other work and is no longer one.  Therefore I'm closing it.

**Closed by AmandaBirmingham** 2019-04-25 22:31 UTC
