### ISSUE TITLE
__eq__ tests different state than what __hash__ is derived from

### ISSUE THREAD

**Issue by wasade** [jdereus/labman#493] opened 2019-05-02 21:05 UTC
See the discussion [here](https://github.com/jdereus/labman/pull/489#discussion_r280506202), this impacts `LabControlObject`.

**Comment by charles-cowart** [comment] 2019-05-03 01:55
Closing as a duplicate of the more detailed https://github.com/jdereus/labman/issues/494

**Closed by charles-cowart** 2019-05-03 01:55 UTC
