### ISSUE TITLE
When plating samples and I select one from drop down menu, it auto fills into two cells. 

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#180] opened 2018-01-31 22:23 UTC
See imagine 
![Uploading Screen Shot 2018-01-31 at 2.21.56 PM.png…]()

**Comment by josenavas** [comment] 2018-01-31 22:25
Duplicate of https://github.com/jdereus/labman/issues/178

**Closed by josenavas** 2018-01-31 22:25 UTC
