### ISSUE TITLE
Add human filtering flag column to shotgun sample sheets

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#212] opened 2018-03-13 16:44 UTC
We're planning on modifying the downstream sample demultiplexing pipeline to automatically filter out human reads from human-derived shotgun sequencing. This should be able to be done on a per-sample basis automatically if we include this as a flag in the sample sheet. 

To allow this behavior, we'll need to: 

- [ ] Modify sample sheet generation routine to pull metadata to look for host taxon ID 
- [ ] Add column to sample sheet with a 'filter human' boolean value
- [ ] Modify the sequencing page to have a check box to disable automatic filtering (maybe?)

**Comment by AmandaBirmingham** [comment] 2018-11-16 21:18
Closed as duplicate of #227

**Closed by AmandaBirmingham** 2018-11-16 21:18 UTC
Labels: duplicate
